# Generated by Django 4.2.6 on 2024-01-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0004_itemtransactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtransactionhistory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='itemtransactionhistory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemtransactionhistory',
            name='staff',
        ),
        migrations.DeleteModel(
            name='ItemModel',
        ),
        migrations.DeleteModel(
            name='ItemTransactionHistory',
        ),
    ]
