# Generated by Django 4.2.6 on 2024-01-05 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0005_remove_itemtransactionhistory_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('gstin', models.CharField(max_length=16)),
                ('gst_type', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('opening_balance', models.FloatField(default=0)),
                ('to_pay', models.BooleanField(null=True)),
                ('to_recieve', models.BooleanField(null=True)),
                ('date', models.DateField(null=True)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2024, 1, 5))),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('party', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.parties')),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
