# Generated by Django 4.2.6 on 2024-01-06 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BillSoftwareapp', '0008_alter_history_date_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_current_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_sale_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_taxable',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='item_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ItemUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255, null=True)),
                ('trans_invoice', models.PositiveBigIntegerField(blank=True, null=True)),
                ('trans_user_name', models.CharField(max_length=255, null=True)),
                ('trans_date', models.DateTimeField(null=True)),
                ('trans_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_current_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_adjusted_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_price', models.PositiveBigIntegerField(default=0)),
                ('trans_status', models.CharField(max_length=255, null=True)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(max_length=255, null=True)),
                ('done_by_name', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.staff_details')),
            ],
        ),
    ]
