# Generated by Django 4.2.6 on 2024-01-08 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0009_itemmodel_item_current_stock_itemmodel_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='idate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='party_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='returnno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='state_of_supply',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 8)),
        ),
    ]
