# Generated by Django 4.2.6 on 2024-01-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0011_creditnote_cgst_creditnote_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='slno',
        ),
    ]
