# Generated by Django 4.2.6 on 2024-02-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0012_remove_creditnoteitem_slno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 3)),
        ),
    ]
