# Generated by Django 4.2.6 on 2024-02-06 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0013_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='refno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 6)),
        ),
    ]
