# Generated by Django 4.2.6 on 2024-02-09 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0016_alter_history_date_creditnotehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotehistory',
            name='party',
        ),
        migrations.AddField(
            model_name='creditnotehistory',
            name='transactiondate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditnotehistory',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 9)),
        ),
    ]
