# Generated by Django 4.2.6 on 2024-02-10 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0017_remove_creditnotehistory_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotehistory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotehistory',
            name='action',
            field=models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 10)),
        ),
    ]
