# Generated by Django 4.2.6 on 2024-02-13 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0018_creditnotehistory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoteitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.itemmodel'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 13)),
        ),
    ]
