# Generated by Django 4.2.6 on 2024-02-16 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0019_creditnoteitem_item_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotehistory',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.parties'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 16)),
        ),
    ]
