# Generated by Django 4.2.6 on 2024-02-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0021_remove_creditnotehistory_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotehistory',
            name='name',
        ),
    ]
