# Generated by Django 4.2.6 on 2024-03-06 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0022_remove_creditnotehistory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 6)),
        ),
    ]
